services:
  db:
      image: postgres:16
      container_name: twa-postgres
      env_file:
        - .env
      ports:
        - "5432:5432"
      volumes:
        - twa_pgdata:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U twa -d twa"]
        interval: 5s
        timeout: 3s
        retries: 10

  api:
    build: .
    container_name: twa-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/twa
      SPRING_DATASOURCE_USERNAME: twa
      SPRING_DATASOURCE_PASSWORD: twa
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
  twa_pgdata:
